export const ACTypes = {
  SET_AUTH_USER: "SET_AUTH_USER",
  SET_AUTH_BUSINESS: "SET_AUTH_BUSINESS",
  SIGNOUT: "SIGNOUT",
  SET_ACTIVE_BOXES: "SET_ACTIVE_BOXES",
  ADD_NEW_BOX: "ADD_NEW_BOX",
  EDIT_BOX: "EDIT_BOX",
  DELETE_BOX: "DELETE_BOX",

  UPDATE_PROFILE: "UPDATE_PROFILE",
  SET_USER_LOCATION: "SET_USER_LOCATION",

  SET_ALL_BOXES: "GET_ALL_BOXES",
  UPDATE_BOX_DATA: "UPDATE_BOX_DATA",
  SET_ALL_CUISINE: "GET_ALL_CUISINE",
  SET_ACTIVE_ORDERS: "SET_ACTIVE_ORDERS",
  DELETE_ORDER: "DELETE_ORDER",
  DELETE_ALL_BOXES: "DELETE_ALL_BOXES",
  DELETE_ALL_ORDERS: "DELETE_ALL_ORDERS"
};
